fileName <- "household_power_consumption.txt"
powerData <- read.table(fileName, header=TRUE, sep=";", stringsAsFactors=FALSE, dec=".")
twoMonthData<-subset(powerData,Date %in% c("1/2/2007","2/2/2007"))
datetime <- strptime(paste(twoMonthData$Date, twoMonthData$Time, sep=" "), "%d/%m/%Y %H:%M:%S")
png("plot3.png",width=480,height=480)
plot(datetime, as.numeric(twoMonthData$Sub_metering_1), type="l", xlab="", ylab="Energy Submetering")
lines(datetime, as.numeric(twoMonthData$Sub_metering_2), type="l",col = "red")
lines(datetime, as.numeric(twoMonthData$Sub_metering_3), type="l",col = "blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, lwd=2.5, col=c("black", "red", "blue"))    
dev.off()
